#+BEGIN_EXPORT html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<title>make-core</title>
  <style type="text/css">
body {
    margin-left: 5%;
    margin-right: 5%;
    font-family: Times, serif;
    font-size: 110%;
}

h1, h2, h3, h4, h5, h6, p {
    font-family: Times, serif;
}

dt {
    font-weight: bold
}

pre {
    font-family: Courier New, monospace;
    font-size: 100%;
    font-weight: bold
}

ins {
    color: green;
}

del {
    color: red;
}

dt {
    font-weight: bold
}

p.red {
    color: red;
}

span.red {
    color: red;
}

div.red {
    color: red;
}

blockquote {
    margin-left: 5%;
    margin-right: 5%;
    font-family: Times, serif;
    font-style: italic;
    text-align: left;
    text-indent: 0px;
}
  </style>
</head>
<body>
#+END_EXPORT
* WP-contact-2-post

- Version: VERSION

- Create a "Pending" post from a Contact Form 7 submission, after
  Flamingo saves it. The post content comes from a template page.

- See readme.txt for the user documentation.

** How it works

- store-cf7-file-uploads saves images in wpcf7_before_send_mail and
  fires nmr_create_attachment_id_generated. This plugin collects
  those IDs.
- Flamingo saves the message in wpcf7_submit, then fires
  wpcf7_after_flamingo with flamingo_inbound_id. This plugin hooks
  that action, so no post is made when Flamingo does not store the
  message (do_not_store: true), or for spam.
- The form's "create_post" and "post_template" Additional Settings
  are read with WPCF7_ContactForm::is_true() and pref().
- The template page is split with parse_blocks(). Attribute blocks
  are removed, [field] is replaced only in the block HTML (not in the
  block comment JSON), then serialize_blocks().

** Notes

- File fields: CF7 saves a hash of the file as the field value, so
  [file-field] in a template shows that hash. The images are attached
  to the post instead.
- store-cf7-file-uploads only saves image files.
- Post author is the user with the site's admin_email, else the
  lowest ID administrator. Content is still filtered by core kses,
  because kses checks the submitter (not logged in), not the author.
- If publish-date is valid, the date is fixed (post_date_gmt is set),
  so publishing keeps it; a future date makes the post "Scheduled".
  If there is no valid publish-date, the post date "floats": it is
  set when the post is published.
- ninja-auto-post-expire only acts on posts if its "Post" option is
  set to "Yes" in Settings, Post Expire Settings.

** Test

- test/setup.php and test/submit.php are run with wp-cli on a test
  site with all the plugins active. They are not in the dist zip.

#+BEGIN_SRC bash
wp eval-file test/setup.php
wp eval-file test/submit.php full attach   # post, attachment, expiry
wp eval-file test/submit.php notitle       # title UNDEFINED
wp eval-file test/submit.php nostore       # no post
wp eval-file test/submit.php nocreate      # no post
wp eval-file test/submit.php badslug       # no post, error_log
wp eval-file test/submit.php full spam     # no post
wp post list --post_type=post --post_status=pending
#+END_SRC
